### ISSUE TITLE
Support for Python3 and Qt5 ?

### ISSUE THREAD

**Issue by luzpaz** [davidmubernal/MakerWorkbench_Documentation#10]
In the README it says support for version 0.18, does it support 0.19 with py3/Qt5 ?

**Comment by davidmubernal** [comment]
The Workbench support py3 and  I use pyside2 to the GUI but I think Qt5 is also support.
I did some test with FreeCAD 0.19 and it works fine.

I haven't updated the README because I'm working on a new version of the Workbench, but I don't know when it will be available.
