### ISSUE TITLE
screencasts (gif or yotube) of workbench in action

### ISSUE THREAD

**Issue by luzpaz** [davidmubernal/MakerWorkbench_Documentation#9]
It would be nice to see this in the README for better comprehension of how the workbench operates

**Comment by davidmubernal** [comment]
I was thinking of doing some Workbench tutorial videos. At the moment, there are two tutorials available on the [website](https://mechatronic.readthedocs.io/en/master/Tutorial.html).

I will add the idea to a new project _[Issues to solve](https://github.com/davidmubernal/Mechatronic/projects/4)_ 

I hope the tutorials help you to know how it works and thanks you for the idea
